spring:
  application:
    name: usercenter
  #session失效时间
  session:
    timeout: 86400
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userCenter?serverTimezone=UTC
    username: xuan
    password: 970813czx
server:
  port: 8081
  servlet:
    context-path: /api




