spring:
  application:
    name: usercenter
  #session失效时间
  session:
    timeout: 86400
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi-user-center?serverTimezone=UTC
    username: root
    password: root
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#方法2：在同一个application.yml中配置多环境
#---
#
#spring:
#  config:
#    activate:
#      on-profile: test
#
#server:
#  port: 8082
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: production
#
#
#server:
#  port: 8081


